### ISSUE TITLE
undo-history-summary, NoMethodError

### ISSUE THREAD

**Issue by shawn0915** [jeremycole/innodb_ruby#100]
Hello, Dear @jeremycole
I'm trying the latest version on innodb_ruby, but when I test this case, meet an error, when you have time, could you please take a look?

> Case: [undo-history-summary](https://github.com/jeremycole/innodb_ruby/wiki#undo-history-summary)

Test env: Ruby 2.6 & MySQL 5.6 & MariaDB 10.2 with sakiladb
```
docker run --name mysql-5.6 -v /data/my56:/var/lib/mysql -d mysql:5.6
docker run --name mariadb-10.2 -v /data/mdb2:/var/lib/mysql -d mariadb:10.2
```
> error msg

- MySQL 5.6
```
$ innodb_space -s ibdata1 undo-history-summary
Traceback (most recent call last):
    9: from /usr/local/bin/innodb_space:23:in `<main>'
    8: from /usr/local/bin/innodb_space:23:in `load'
    7: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/bin/innodb_space:1715:in `<top (required)>'
    6: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/bin/innodb_space:1202:in `undo_history_summary'
    5: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/bin/innodb_space:1202:in `reject'
    4: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/bin/innodb_space:1202:in `each'
    3: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/lib/innodb/history.rb:25:in `each_history_list'
    2: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/lib/innodb/history.rb:25:in `each'
    1: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/lib/innodb/history.rb:26:in `block in each_history_list'
/usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/bin/innodb_space:1202:in `block in undo_history_summary': undefined method `empty?' for #<Innodb::List::History:0x0000562fac3518d0> (NoMethodError)
```

- MariaDB 10.2

```
$ innodb_space -s ibdata1 undo-history-summary
Traceback (most recent call last):
    9: from /usr/local/bin/innodb_space:23:in `<main>'
    8: from /usr/local/bin/innodb_space:23:in `load'
    7: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/bin/innodb_space:1715:in `<top (required)>'
    6: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/bin/innodb_space:1202:in `undo_history_summary'
    5: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/bin/innodb_space:1202:in `reject'
    4: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/bin/innodb_space:1202:in `each'
    3: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/lib/innodb/history.rb:25:in `each_history_list'
    2: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/lib/innodb/history.rb:25:in `each'
    1: from /usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/lib/innodb/history.rb:26:in `block in each_history_list'
/usr/local/lib/ruby/gems/2.6.0/gems/innodb_ruby-0.11.0/bin/innodb_space:1202:in `block in undo_history_summary': undefined method `empty?' for #<Innodb::List::History:0x000055c85a01d830> (NoMethodError)
```

**Comment by jeremycole** [comment]
I am not sure when this method disappeared, but it did. I added back an implementation and a very basic test. Sorry it took a while to get to this!
