### ISSUE TITLE
Errno::ENOENT

### ISSUE THREAD

**Issue by PapaOfficial** [jeremycole/innodb_ruby#175]
Hello, I tries to install and use innodb_ruby, but it does not work, this error appears all the time

$ innodb_space -s ibdata1 system-spaces
Traceback (most recent call last):
	13: from /usr/local/bin/innodb_space:23:in `<main>'
	12: from /usr/local/bin/innodb_space:23:in `load'
	11: from /Library/Ruby/Gems/2.6.0/gems/innodb_ruby-0.12.0/bin/innodb_space:1599:in `<top (required)>'
	10: from /Library/Ruby/Gems/2.6.0/gems/innodb_ruby-0.12.0/bin/innodb_space:1599:in `new'
	 9: from /Library/Ruby/Gems/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/system.rb:41:in `initialize'
	 8: from /Library/Ruby/Gems/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/system.rb:60:in `add_space_file'
	 7: from /Library/Ruby/Gems/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/system.rb:60:in `new'
	 6: from /Library/Ruby/Gems/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:65:in `initialize'
	 5: from /Library/Ruby/Gems/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:65:in `each'
	 4: from /Library/Ruby/Gems/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:66:in `block in initialize'
	 3: from /Library/Ruby/Gems/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:66:in `new'
	 2: from /Library/Ruby/Gems/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:45:in `initialize'
	 1: from /Library/Ruby/Gems/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:45:in `open'
/Library/Ruby/Gems/2.6.0/gems/innodb_ruby-0.12.0/lib/innodb/space.rb:45:in `initialize': No such file or directory @ rb_sysopen - ibdata1 (Errno::ENOENT)

Reinstall of MySQL and innodb_ruby doesn't help, unfortunately

**Comment by PapaOfficial** [comment]
mysql 8.0 is not supported
