### ISSUE TITLE
Do I mistake the use of index-recurse?

### ISSUE THREAD

**Issue by kysnm** [jeremycole/innodb_ruby#32]
I made some dummy data using this rake task.
https://github.com/kysnm/innodb_ruby_test/blob/master/Rakefile

and I'm trying index-recurse with this class.
https://github.com/kysnm/innodb_ruby_test/blob/master/innodb_ruby_test_db.rb#L15-L20

but error occured like below.
```bash
➜  innodb_ruby_test git:(master) ✗ bundle exec innodb_space -f /usr/local/var/mysql/innodb_ruby_test/users.ibd -p 3 -r innodb_ruby_test_db.rb -d InnodbRubyTest_users_state index-recurse
ROOT NODE #3: 618 records, 8652 bytes
/tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/gems/innodb_ruby-0.9.13/lib/innodb/page.rb:44:in `initialize': Page can't be initialized from nil space or buffer (space: #<Innodb::Space:0x007fc3ba0d01f8>, buffer: ) (RuntimeError)
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/gems/innodb_ruby-0.9.13/lib/innodb/page.rb:24:in `new'
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/gems/innodb_ruby-0.9.13/lib/innodb/page.rb:24:in `parse'
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/gems/innodb_ruby-0.9.13/lib/innodb/space.rb:231:in `page'
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/gems/innodb_ruby-0.9.13/lib/innodb/index.rb:31:in `page'
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/gems/innodb_ruby-0.9.13/lib/innodb/index.rb:59:in `block in _recurse'
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/gems/innodb_ruby-0.9.13/lib/innodb/page/index.rb:944:in `block in each_child_page'
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/gems/innodb_ruby-0.9.13/lib/innodb/page/index.rb:908:in `each_record'
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/gems/innodb_ruby-0.9.13/lib/innodb/page/index.rb:943:in `each_child_page'
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/gems/innodb_ruby-0.9.13/lib/innodb/index.rb:58:in `_recurse'
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/gems/innodb_ruby-0.9.13/lib/innodb/index.rb:73:in `recurse'
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/gems/innodb_ruby-0.9.13/bin/innodb_space:1274:in `index_recurse'
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/gems/innodb_ruby-0.9.13/bin/innodb_space:1834:in `<top (required)>'
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/bin/innodb_space:23:in `load'
	from /tmp/.rbenv/versions/2.3.0-preview2/gemsets/innodb_ruby_test/bin/innodb_space:23:in `<main>'
```

Do I have something wrong?
Please tell me correct usage.

P.S.
The following will work correctly.
```bash
bundle exec innodb_space -s /usr/local/var/mysql/ibdata1 -T innodb_ruby_test/users -r innodb_ruby_test_db.rb -d InnodbRubyTest_users_state -I state_idx index-recurse
```

and index added manually.
https://gist.github.com/kysnm/44ea60a72546c9860093

**Comment by darnaut** [comment]
You need to wait for the table data to be flushed to disk, or force it to be flushed.

Suggest executing ```FLUSH TABLES tbl_name FOR EXPORT``` before attempting to read it from disk.
