### ISSUE TITLE
innodb_space space-indexes crash when observed page_no == FIL_NULL

### ISSUE THREAD

**Issue by artyomtz** [jeremycole/innodb_ruby#36]
```
008816   00000000000319a4                  space[ibdata1].page[11,INDEX].record[8816].key[TABLE_ID].BIGINT UNSIGNED
008824   00000000000319e9                  space[ibdata1].page[11,INDEX].record[8816].key[ID].BIGINT UNSIGNED
008832   000008f6812c                      space[ibdata1].page[11,INDEX].record[8816].sys[DB_TRX_ID].TRX_ID.transaction_id
008838   d100000141069a                    space[ibdata1].page[11,INDEX].record[8816].sys[DB_ROLL_PTR].ROLL_PTR
008845   6d6574615f76616c75655f696478      space[ibdata1].page[11,INDEX].record[8816].row[NAME].VARCHAR(100)
008859   00000001                          space[ibdata1].page[11,INDEX].record[8816].row[N_FIELDS].INT UNSIGNED
008863   00000020                          space[ibdata1].page[11,INDEX].record[8816].row[TYPE].INT UNSIGNED
008867   00031996                          space[ibdata1].page[11,INDEX].record[8816].row[SPACE].INT UNSIGNED
008871   ffffffff                          space[ibdata1].page[11,INDEX].record[8816].row[PAGE_NO].INT UNSIGNED

/usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/index.rb:32:in `page': Page 4294967295 couldn't be read (RuntimeError)
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/index.rb:13:in`initialize'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/space.rb:309:in `new'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/space.rb:309:in`index'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/space.rb:346:in `block in each_index'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/space.rb:322:in`block in each_index_root_page_number'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/data_dictionary.rb:449:in `block in each_index_by_space_id'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/data_dictionary.rb:365:in`block in each_index'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/data_dictionary.rb:326:in `block in each_record_from_data_dictionary_index'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/index.rb:188:in`block (2 levels) in each_record'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/page/index.rb:908:in `each_record'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/index.rb:187:in`block in each_record'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/index.rb:177:in `block in each_page_at_level'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/index.rb:164:in`each_page_from'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/index.rb:177:in `each_page_at_level'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/index.rb:186:in`each_record'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/data_dictionary.rb:325:in `each_record_from_data_dictionary_index'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/data_dictionary.rb:364:in`each_index'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/data_dictionary.rb:448:in `each_index_by_space_id'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/space.rb:321:in`each_index_root_page_number'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/lib/innodb/space.rb:345:in `each_index'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/bin/innodb_space:426:in`space_indexes'
    from /usr/local/share/gems1.9/gems/innodb_ruby-0.9.13/bin/innodb_space:1818:in `<top (required)>'
    from /usr/local/bin/innodb_space:23:in`load'
    from /usr/local/bin/innodb_space:23:in `<main>'
```

**Comment by jeremycole** [comment]
I suspect this was probably due to running `innodb_space` against a running server and is the type of crash that could be expected in that case. Sometimes the data structures on disk are not in a completely usable state. I am not sure we could do better than the exception raised here.
