### ISSUE TITLE
mysql8.0 support

### ISSUE THREAD

**Issue by longhaiqwe** [jeremycole/innodb_ruby#41]
I use `innodb_space` for mysql8.0 ibdata1, the following errors occured：
```shell
$ innodb_space -s ~/install/mysql8.0/data/ibdata1 system-spaces
name                            pages       indexes
/home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/lib/innodb/index.rb:33:in `page': undefined method `record_describer=' for #<Innodb::Page::FspHdrXdes:0x00000000ef85f8> (NoMethodError)
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/lib/innodb/index.rb:13:in `initialize'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/lib/innodb/space.rb:308:in `new'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/lib/innodb/space.rb:308:in `index'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/lib/innodb/data_dictionary.rb:282:in `data_dictionary_index'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/lib/innodb/data_dictionary.rb:325:in `each_record_from_data_dictionary_index'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/lib/innodb/data_dictionary.rb:364:in `each_index'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/lib/innodb/data_dictionary.rb:448:in `each_index_by_space_id'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/lib/innodb/space.rb:320:in `each_index_root_page_number'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/lib/innodb/space.rb:344:in `each_index'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/bin/innodb_space:207:in `each'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/bin/innodb_space:207:in `to_a'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/bin/innodb_space:207:in `block in system_spaces'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/bin/innodb_space:211:in `call'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/bin/innodb_space:211:in `system_spaces'
        from /home/longhai/.gem/ruby/gems/innodb_ruby-0.9.15/bin/innodb_space:1976:in `<top (required)>'
        from /home/longhai/bin/innodb_space:23:in `load'
        from /home/longhai/bin/innodb_space:23:in `<main>'
```
Does innodb_ruby is still not supported for mysql8.0?(I tested mysql5.7, it's ok)
If so, do we have a plan to support mysql8.0?

**Comment by sunbains** [comment]
8.0 support should be fairly easy (in theory). Dump the table space meta data using ibd2sdi and then parsing the output. ibd2sdi spits out the data in JSON format, there must be JSON parsers in Ruby that should make this task easier.

Any takers? :)

**Comment by junsionzhang** [comment]
> 8.0 support should be fairly easy (in theory). Dump the table space meta data using ibd2sdi and then parsing the output. ibd2sdi spits out the data in JSON format, there must be JSON parsers in Ruby that should make this task easier.
> 
> Any takers? :)

it would be awesome if someone can give the details or tools/

**Comment by jeremycole** [comment]
I created a blanket issue for MySQL 8.0 support, so I will consolidate the info and work there: https://github.com/jeremycole/innodb_ruby/issues/97.
