### ISSUE TITLE
space-extents-illustrate produce undefined method `ibuf_index?'

### ISSUE THREAD

**Issue by clevertension** [jeremycole/innodb_ruby#58]
OS: 10.15.7
Ruby: 2.6.3p62

when i execute
`
innodb_space -s ibdata1 -T my_test/agent space-extents-illustrate
`

` Start Page ╭────────────────────────────────────────────────────────────────╮
Traceback (most recent call last):
	24: from /Users/dan/MySQL/innodb_ruby/bin/innodb_space:1669:in `<main>'
	23: from /Users/dan/MySQL/innodb_ruby/bin/innodb_space:513:in `space_extents_illustrate'
	22: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/space.rb:470:in `each_xdes'
	21: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/space.rb:457:in `each_xdes_page'
	20: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/space.rb:445:in `each_xdes_page_number'
	19: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/space.rb:445:in `each'
	18: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/space.rb:446:in `block in each_xdes_page_number'
	17: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/space.rb:459:in `block in each_xdes_page'
	16: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/space.rb:471:in `block in each_xdes'
	15: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/page/fsp_hdr_xdes.rb:144:in `each_xdes'
	14: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/util/buffer_cursor.rb:136:in `name'
	13: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/page/fsp_hdr_xdes.rb:145:in `block in each_xdes'
	12: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/page/fsp_hdr_xdes.rb:145:in `times'
	11: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/page/fsp_hdr_xdes.rb:146:in `block (2 levels) in each_xdes'
	10: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/space.rb:474:in `block (2 levels) in each_xdes'
	 9: from /Users/dan/MySQL/innodb_ruby/bin/innodb_space:516:in `block in space_extents_illustrate'
	 8: from /Users/dan/MySQL/innodb_ruby/bin/innodb_space:465:in `space_extents_illustrate_page_status'
	 7: from /Users/dan/MySQL/innodb_ruby/bin/innodb_space:465:in `each_with_object'
	 6: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/xdes.rb:119:in `each_page_status'
	 5: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/xdes.rb:119:in `each_with_index'
	 4: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/xdes.rb:119:in `each_byte'
	 3: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/xdes.rb:120:in `block in each_page_status'
	 2: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/xdes.rb:120:in `each'
	 1: from /Users/dan/.gem/ruby/2.6.0/gems/innodb_ruby-0.9.16/lib/innodb/xdes.rb:127:in `block (2 levels) in each_page_status'
/Users/dan/MySQL/innodb_ruby/bin/innodb_space:481:in `block in space_extents_illustrate_page_status': undefined method `ibuf_index?' for #<Innodb::Page::Index:0x00007f996788a2e0> (NoMethodError)`

**Comment by clevertension** [comment]
it is fixed now
